### PR TITLE
Implemented a Logger Helper class

### PR DESCRIPTION
**Pull request by Nefarion**
- Changed one enum Flag at RoadManager.cs:126

It now logs to game console (F7) too!

### CODE REVIEW

**Comment by joaofarias** [comment]
Thank you! I'll merge it soon. :)

Any special reason for changing the flag?

**Comment by Nefarion** [comment]
Now its truly every flag :> and not just a "magic number" :+1:

**Comment by Nefarion** [comment]
Damn that button.... my bad

**Comment by joaofarias** [comment]
But it was magic and future-proof :P

You're right, though. Magic numbers are dangerous.

**Comment by Nefarion** [comment]
i can leave it out if you prefer it.

**Comment by joaofarias** [comment]
Nah.. It's ok :)

**Pull request merged**
